/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.victor.pe.cpresentacion;

import java.awt.BorderLayout;

/**
 *
 * @author Alumno-PB203
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCalculadora = new javax.swing.JMenu();
        btMenuCalculadora = new javax.swing.JMenuItem();
        btMenuContador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        btnTipoDocumento = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion en Java Swing");

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setLayout(new java.awt.BorderLayout());

        jMenuBar1.setOpaque(true);

        jMenuCalculadora.setText("Aplicaciones");

        btMenuCalculadora.setText("Calculadora");
        btMenuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuCalculadoraActionPerformed(evt);
            }
        });
        jMenuCalculadora.add(btMenuCalculadora);

        btMenuContador.setText("Contador");
        btMenuContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuContadorActionPerformed(evt);
            }
        });
        jMenuCalculadora.add(btMenuContador);

        jMenuBar1.add(jMenuCalculadora);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Mantenimiento");

        btnTipoDocumento.setText("TipoDocumento");
        btnTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoDocumentoActionPerformed(evt);
            }
        });
        jMenu1.add(btnTipoDocumento);

        jMenuItem1.setText("Genero");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Persona");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Window");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuContadorActionPerformed
        // TODO add your handling code here:
        Contador con = new Contador();
        con.setSize(443, 536);
        con.setLocation(0, 0);
        Principal.removeAll();
        Principal.add(con,BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();
    }//GEN-LAST:event_btMenuContadorActionPerformed

    private void btMenuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuCalculadoraActionPerformed
        Calculadora cal = new Calculadora();
        cal.setSize(413, 655);
        cal.setLocation(0, 0);
        Principal.removeAll();
        Principal.add(cal,BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();
    }//GEN-LAST:event_btMenuCalculadoraActionPerformed

    private void btnTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoDocumentoActionPerformed
        JPanelTipoDocumento td = new JPanelTipoDocumento();
        td.setSize(1100, 600);
        td.setLocation(0, 0);
        Principal.removeAll();
        Principal.add(td,BorderLayout.CENTER);
        Principal.revalidate();
        Principal.repaint();
    }//GEN-LAST:event_btnTipoDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Principal;
    private javax.swing.JMenuItem btMenuCalculadora;
    private javax.swing.JMenuItem btMenuContador;
    private javax.swing.JMenuItem btnTipoDocumento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCalculadora;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
