/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.victor.pe.cpresentacion;

import com.victor.pe.cmodelo.TipoDocumento;
import com.victor.pe.cnegocio.TipoDocumentoBO;
import java.sql.SQLException;
import java.text.ParseException;

/**
 *
 * @author Soporte
 */
public class JPanelTipoDocumento extends javax.swing.JPanel {
    TipoDocumentoBO tdbo = new TipoDocumentoBO();
    TipoDocumento td = new TipoDocumento();
    
    
    //instanciar o invocar
    //

    /**
     * Creates new form JPanelTipoDocumento
     */
    public JPanelTipoDocumento() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoDocumento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTipoDocumento = new javax.swing.JTable();
        CRUDTipoDocumento = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        TextNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextSigla = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFechaActualiza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextOrden = new javax.swing.JTextField();
        TextEstado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        TipoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        TipoDocumento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaTipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaTipoDocumento);

        TipoDocumento.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        CRUDTipoDocumento.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        CRUDTipoDocumento.setText("CRUD Tipo Documento");
        TipoDocumento.add(CRUDTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 68, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        TipoDocumento.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, -1, -1));

        btnModificar.setBackground(new java.awt.Color(102, 204, 255));
        btnModificar.setText("Modificar");
        TipoDocumento.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, -1, -1));

        TextNombre.setForeground(new java.awt.Color(204, 204, 204));
        TextNombre.setBorder(null);
        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        TipoDocumento.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 290, 20));

        jLabel1.setText("Nombre");
        TipoDocumento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel2.setText("Sigla");
        TipoDocumento.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        TextSigla.setForeground(new java.awt.Color(204, 204, 204));
        TextSigla.setBorder(null);
        TipoDocumento.add(TextSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 290, 20));

        jLabel5.setText("Fecha Actualiza");
        TipoDocumento.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        TextFechaActualiza.setForeground(new java.awt.Color(204, 204, 204));
        TextFechaActualiza.setBorder(null);
        TipoDocumento.add(TextFechaActualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 290, 20));

        jLabel3.setText("Orden");
        TipoDocumento.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel4.setText("Estado");
        TipoDocumento.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        TextOrden.setForeground(new java.awt.Color(204, 204, 204));
        TextOrden.setBorder(null);
        TipoDocumento.add(TextOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 290, 20));

        TextEstado.setForeground(new java.awt.Color(204, 204, 204));
        TextEstado.setBorder(null);
        TipoDocumento.add(TextEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 290, 20));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 290, 10));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 290, 10));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 290, 10));

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        TipoDocumento.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        TipoDocumento.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 290, 10));

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 290, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            td.setNombre(TextNombre.getText());
            td.setEstado(TextEstado.getText());
            td.setOrden(Integer.parseInt(TextEstado.getText()));
            td.setSigla(TextSigla.getText());
            td.setFechaActualiza(TextFechaActualiza.getText());
            tdbo.agregarTipoDocumento(td);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CRUDTipoDocumento;
    private javax.swing.JTable TablaTipoDocumento;
    private javax.swing.JTextField TextEstado;
    private javax.swing.JTextField TextFechaActualiza;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextOrden;
    private javax.swing.JTextField TextSigla;
    private javax.swing.JPanel TipoDocumento;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
