/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.victor.pe.cpresentacion;

import com.victor.pe.cmodelo.TipoDocumento;
import com.victor.pe.cnegocio.TipoDocumentoBO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Soporte
 */
public class JPanelTipoDocumento extends javax.swing.JPanel {
    TipoDocumentoBO tdbo = new TipoDocumentoBO();
    TipoDocumento td = new TipoDocumento();
    
        public JPanelTipoDocumento() {
        initComponents();
        listarTipoDocumento();
    }
    
        public void listarTipoDocumento(){
        tdbo.listarTipoDocumento(TablaTipoDocumento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoDocumento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTipoDocumento = new javax.swing.JTable();
        CRUDTipoDocumento = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        TxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtSigla = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtFechaActualiza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtOrden = new javax.swing.JTextField();
        TxtEstado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        TipoDocumento.setBackground(new java.awt.Color(255, 255, 255));
        TipoDocumento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaTipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaTipoDocumento);

        TipoDocumento.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, 360));

        CRUDTipoDocumento.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        CRUDTipoDocumento.setText("CRUD Tipo Documento");
        TipoDocumento.add(CRUDTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 68, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        TipoDocumento.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, -1, -1));

        btnModificar.setBackground(new java.awt.Color(102, 204, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        TipoDocumento.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));

        TxtNombre.setBorder(null);
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        TipoDocumento.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 290, 20));

        jLabel1.setText("Nombre");
        TipoDocumento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel2.setText("Sigla");
        TipoDocumento.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        TxtSigla.setBorder(null);
        TipoDocumento.add(TxtSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 290, 20));

        jLabel5.setText("Fecha Actualiza");
        TipoDocumento.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        TxtFechaActualiza.setBorder(null);
        TipoDocumento.add(TxtFechaActualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 290, 20));

        jLabel3.setText("Orden");
        TipoDocumento.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel4.setText("Estado");
        TipoDocumento.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        TxtOrden.setBorder(null);
        TipoDocumento.add(TxtOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 290, 20));

        TxtEstado.setBorder(null);
        TipoDocumento.add(TxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 290, 20));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 290, 10));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 290, 10));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 290, 10));

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        TipoDocumento.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        TipoDocumento.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 290, 10));

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        TipoDocumento.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 290, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        /*try {
            td.setNombre(TxtNombre.getText());
            td.setEstado(TxtEstado.getText());
            td.setOrden(Integer.parseInt(TxtOrden.getText()));
            td.setSigla(TxtSigla.getText());
            td.setFechaActualiza(TxtFechaActualiza.getText());          
            tdbo.agregarTipoDocumento(td); 
            JOptionPane.showMessageDialog(null, ":) se guardo corectamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");
        }*/
try {
    // Validar si los campos no están vacíos
    if (TxtNombre.getText().isEmpty() || TxtEstado.getText().isEmpty() || TxtOrden.getText().isEmpty() || TxtSigla.getText().isEmpty() || TxtFechaActualiza.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        return;
    }
    
    // Asignar los valores de los campos al objeto td (TipoDocumento)
    td.setNombre(TxtNombre.getText());
    td.setEstado(TxtEstado.getText());
    
    // Validar y asignar el valor de Orden
    try {
        td.setOrden(Integer.parseInt(TxtOrden.getText()));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Orden debe ser un número.");
        return; // Detener ejecución si no es un número
    }
    
    td.setSigla(TxtSigla.getText());
    
    // Validar y convertir el formato de la fecha
    try {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yy"); // Formato de la fecha esperado
        Date fecha = sdf.parse(TxtFechaActualiza.getText()); // Convertir el texto a una fecha
        String fechaString = sdf.format(fecha); // Convertir la fecha a String
        td.setFechaActualiza(fechaString); // Asignar la fecha convertida al objeto td

    } catch (ParseException pe) {
        JOptionPane.showMessageDialog(null, "Error: Formato de fecha incorrecto. Use dd-MM-yy.");
        return; // Detener ejecución si la fecha no es válida
    }
    
    // Guardar el objeto td utilizando el método agregarTipoDocumento
    tdbo.agregarTipoDocumento(td);
    
    // Mostrar mensaje de éxito
    JOptionPane.showMessageDialog(null, ":) Se guardó correctamente");
    
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error al guardar Tipo documento en la base de datos: " + e.getMessage());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
}

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            TxtNombre.setText("");
            TxtEstado.setText("");
            TxtOrden.setText("");
            TxtSigla.setText("");
            //txtFechaRegistro.setText("");
            TxtFechaActualiza.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:                                            
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:                                            
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CRUDTipoDocumento;
    private javax.swing.JTable TablaTipoDocumento;
    private javax.swing.JPanel TipoDocumento;
    private javax.swing.JTextField TxtEstado;
    private javax.swing.JTextField TxtFechaActualiza;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtOrden;
    private javax.swing.JTextField TxtSigla;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
